const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

const packageJson = require(path.join(root, "package.json"));
const packageLock = require(path.join(root, "package-lock.json"));
const indexHtml = read("index.html");
const main = read("src/main/main.js");
const preload = read("src/main/preload.js");
const app = read("src/renderer/App.jsx");
const styles = read("src/renderer/styles.css");

assert.equal(packageJson.name, "dl-studio-windows");
assert.equal(packageJson.author, "DL Studio");
assert.equal(packageJson.build.productName, "DL Studio");
assert.equal(packageJson.build.nsis.shortcutName, "DL Studio");
assert.equal(packageLock.name, "dl-studio-windows");
assert.equal(packageLock.packages[""].name, "dl-studio-windows");
assert.match(indexHtml, /<title>DL Studio<\/title>/);

assert.match(main, /const APP_NAME = "DL Studio"/);
assert.match(main, /app\.setName\(APP_NAME\)/);
assert.match(main, /title: APP_NAME/);
assert.doesNotMatch(main, /frame: false/);
assert.match(main, /titleBarStyle: "hiddenInset"/);
assert.match(main, /titleBarStyle: "hidden"/);
assert.match(main, /titleBarOverlay/);
assert.match(main, /function setTitleBarTheme/);
assert.match(main, /setFullScreen\(/);
assert.match(main, /isFullScreen\(/);
assert.doesNotMatch(main, /mainWindow\.maximize\(\)/);
assert.match(main, /before-input-event/);
assert.match(main, /setZoomLevel\(/);
assert.match(main, /input\.alt/);
assert.match(main, /input\.control/);
assert.match(main, /const INFERA_API_BASE_URL = process\.env\.INFERA_API_BASE_URL \|\| process\.env\.VITE_INFERA_API_BASE_URL \|\| "https:\/\/api\.infera\.cn\/api\/infera"/);
assert.match(main, /function resolveInferaUrl/);
assert.match(main, /ipcMain\.handle\("infera:request"/);
assert.match(main, /function uploadInferaVideo/);
assert.match(main, /const activeUploadRequests = new Map/);
assert.match(main, /function normalizeUploadTimestamp/);
assert.match(main, /Math\.round\(timestamp\)/);
assert.match(main, /function emitUploadProgress/);
assert.match(main, /infera:upload-progress/);
assert.match(main, /payload\.uploadId/);
assert.match(main, /bytesUploaded/);
assert.match(main, /speedBytesPerSecond/);
assert.match(main, /\/memory\/assets\/web-video\/events/);
assert.match(main, /multipart\/form-data/);
assert.match(main, /start_timestamp_ms/);
assert.match(main, /parseInferaUploadEvents/);
assert.match(main, /ipcMain\.handle\("infera:upload-video"/);
assert.match(main, /ipcMain\.handle\("infera:cancel-upload"/);
assert.match(main, /function parseFrameRate/);
assert.match(main, /function formatFrameRateLabel/);
assert.match(main, /function parseEncodingProgressLine/);
assert.match(main, /encodingFps/);
assert.match(main, /encodingSpeed/);
assert.match(main, /hardwareEncoding/);
assert.match(main, /const frameRate = parseFrameRate/);
assert.match(main, /frameRate,/);
assert.match(main, /frameRateLabel: formatFrameRateLabel\(frameRate\)/);

assert.match(preload, /toggleFullscreenWindow/);
assert.match(preload, /isWindowFullscreen/);
assert.match(preload, /platform: process\.platform/);
assert.match(preload, /setTitleBarTheme: \(theme\) => ipcRenderer\.invoke\("window:set-title-bar-theme", theme\)/);
assert.match(preload, /onWindowFullscreenChange/);
assert.match(preload, /requestInfera: \(payload\) => ipcRenderer\.invoke\("infera:request", payload\)/);
assert.match(preload, /uploadInferaVideo: \(payload\) => ipcRenderer\.invoke\("infera:upload-video", payload\)/);
assert.match(preload, /cancelInferaUpload: \(uploadId\) => ipcRenderer\.invoke\("infera:cancel-upload", uploadId\)/);
assert.match(preload, /onInferaUploadProgress: \(listener\) => on\("infera:upload-progress", listener\)/);

assert.match(app, /name: "DL Studio"/);
assert.match(app, /SplashScreen/);
assert.match(app, /className="splash-screen"/);
assert.match(app, /build\/icon\.svg/);
assert.match(app, /toggleFullscreenWindow/);
assert.match(app, /isWindowFullscreen/);
assert.match(app, /onWindowFullscreenChange/);
assert.match(app, /const NAV_ITEMS = \["Editor", "Cloud", "Delphi"\]/);
assert.match(app, /const CLOUD_SPACES/);
assert.match(app, /DL Repository/);
assert.match(app, /DL Rawdata/);
assert.match(app, /showLogin/);
assert.match(app, /LoginDialog/);
assert.match(app, /className="profile-button"/);
assert.match(app, /className="top-nav"/);
assert.match(app, /className="nav-underline"/);
assert.match(app, /platform-\$\{dlEditor\.platform \|\| "browser"\}/);
assert.doesNotMatch(app, /title="最小化"/);
assert.doesNotMatch(app, /title=\{isFullscreen \? "退出全屏" : "全屏"\}/);
assert.doesNotMatch(app, /className="chrome-button close"/);
assert.match(styles, /\.app-chrome[\s\S]*height: 42px/);
assert.match(styles, /--chrome-left-inset: 86px/);
assert.match(styles, /--system-window-controls-width: 138px/);
assert.match(styles, /\.app-chrome[\s\S]*padding: 5px calc\(8px \+ var\(--system-window-controls-width\)\) 5px var\(--chrome-left-inset\)/);
assert.match(styles, /\.window-actions[\s\S]*flex: 0 0 auto/);
assert.match(styles, /\.chrome-button[\s\S]*flex: 0 0 var\(--chrome-tool-button-width\)/);
assert.match(styles, /\.app-shell\.platform-win32 \.chrome-button[\s\S]*border-radius: 0/);
assert.match(app, /useLayoutEffect/);
assert.match(app, /navLabelRefs/);
assert.match(app, /getBoundingClientRect/);
assert.match(app, /className="nav-label"/);
assert.match(app, /style=\{navUnderlineStyle\}/);
assert.match(app, /"--nav-underline-width"/);
assert.match(app, /"--nav-underline-left"/);
assert.match(app, /const INFERA_API_BASE_URL = import\.meta\.env\.VITE_INFERA_API_BASE_URL \|\| "https:\/\/api\.infera\.cn\/api\/infera"/);
assert.match(app, /const AUTH_STORAGE_KEY = "dl-studio-auth"/);
assert.match(app, /function inferIdentifierType/);
assert.match(app, /function unwrapInferaResult/);
assert.match(app, /function requestInfera/);
assert.match(app, /typeof dlEditor\.requestInfera === "function"/);
assert.match(app, /dlEditor\.requestInfera\(\{ path, method, token, body \}\)/);
assert.ok(app.includes('const normalizedBase = INFERA_API_BASE_URL.replace(/\\/+$/, "");'));
assert.ok(app.includes('const normalizedPath = rawPath.replace(/^\\/+/, "");'));
assert.ok(app.includes('return new URL(normalizedPath, `${normalizedBase}/`).toString();'));
assert.match(app, /\/auth\/login/);
assert.match(app, /type: inferIdentifierType\(identifier\)/);
assert.match(app, /refreshToken/);
assert.match(app, /Authorization/);
assert.match(app, /Bearer \$\{token\}/);
assert.match(app, /window\.localStorage\?\.setItem\(AUTH_STORAGE_KEY/);
assert.match(app, /activeNav === "Editor"/);
assert.match(app, /activeNav === "Cloud"/);
assert.match(app, /CloudRepository/);
assert.match(app, /loadCloudRepository/);
assert.match(app, /\/device\/files\?limit=50&include_page=true/);
assert.match(app, /repositoryState/);
assert.match(app, /selectionMode/);
assert.match(app, /selectedJobIds/);
assert.match(app, /toggleSelectionMode/);
assert.match(app, /toggleAllSelectedJobs/);
assert.match(app, /backupSelectedJobs/);
assert.match(app, /uploadSelectedJobs/);
assert.match(app, /createUploadItems/);
assert.match(app, /cancelCurrentUpload/);
assert.match(app, /closeUploadPanel/);
assert.match(app, /toggleUploadDetails/);
assert.match(app, /UploadProgressPanel/);
assert.match(app, /uploadId/);
assert.match(app, /onInferaUploadProgress/);
assert.match(app, /speedBytesPerSecond/);
assert.match(app, /formatUploadSpeed/);
assert.match(app, /getUploadCurrentSpeed/);
assert.match(app, /getActiveEncodingJob/);
assert.match(app, /formatEncodingSpeed/);
assert.match(app, /className="encoding-stats-chip"/);
assert.match(app, /activeEncodingJob/);
assert.match(app, /canBackupSelection/);
assert.match(app, /canUploadSelection/);
assert.match(app, /isLowFrameRateJob/);
assert.match(app, /isJobUploadable/);
assert.match(app, /getJobUploadPath/);
assert.match(app, /dlEditor\.uploadInferaVideo/);
assert.match(app, /\/memory\/assets\/web-video\/events/);
assert.match(app, /className="frame-rate-chip"/);
assert.match(app, /className="selection-count"/);
assert.match(app, /className="queue-select-box"/);
assert.match(app, /cloudSpaceId/);
assert.match(app, /setCloudSpaceId/);
assert.match(app, /className="cloud-space-button"/);
assert.match(app, /className="cloud-space-menu"/);
assert.match(app, /title="选择视频"/);
assert.match(app, /title="备份所选视频"/);
assert.match(app, /title="上传到 Delphi Repository"/);
assert.match(app, /const CLOUD_FILTERS/);
assert.match(app, /getCloudRepositoryStats/);
assert.match(app, /cloudQuery/);
assert.match(app, /cloudViewMode/);
assert.match(app, /activeCloudFilter/);
assert.match(app, /className="cloud-drive"/);
assert.match(app, /className="cloud-sidebar"/);
assert.match(app, /className="cloud-search"/);
assert.match(app, /className="cloud-view-toggle"/);
assert.match(app, /className="cloud-file-table"/);
assert.match(app, /className="cloud-file-grid"/);
assert.match(app, /className="repository-list"/);
assert.match(app, /className="repository-item"/);
assert.match(app, /RepositoryGridCard/);
assert.match(app, /RepositoryTableRow/);
assert.match(app, /thumbnail_url/);
assert.match(app, /summary_text/);
assert.match(app, /parse_status/);
assert.match(app, /media_url/);
assert.match(app, /PlaceholderPage/);
assert.match(app, /title=\{activeNav\}/);
assert.match(app, /name="identifier"/);
assert.match(app, /autoComplete="username"/);
assert.match(app, /type="password"/);
assert.match(styles, /\.splash-screen/);
assert.match(styles, /\.profile-button/);
assert.match(styles, /\.top-nav/);
assert.doesNotMatch(styles, /\.top-nav\s*\{[^}]*border:/s);
assert.doesNotMatch(styles, /\.top-nav\s*\{[^}]*background:/s);
assert.match(styles, /\.nav-underline/);
assert.match(styles, /width: var\(--nav-underline-width\)/);
assert.match(styles, /transform: translateX\(var\(--nav-underline-left\)\)/);
assert.match(styles, /\.profile-button svg/);
assert.match(styles, /\.placeholder-page/);
assert.match(styles, /\.cloud-page/);
assert.match(styles, /\.cloud-drive/);
assert.match(styles, /\.cloud-sidebar/);
assert.match(styles, /\.cloud-brand-icon svg/);
assert.match(styles, /\.cloud-space-button/);
assert.match(styles, /\.cloud-space-menu/);
assert.match(styles, /\.cloud-search/);
assert.match(styles, /\.cloud-view-toggle/);
assert.match(styles, /\.cloud-file-table/);
assert.match(styles, /\.cloud-file-grid/);
assert.match(styles, /\.queue-item\.selection-open/);
assert.match(styles, /\.queue-select-box/);
assert.doesNotMatch(styles, /\.queue-select-box\s*\{[^}]*border:/s);
assert.match(styles, /\.selection-count/);
assert.match(styles, /\.frame-rate-chip/);
assert.match(styles, /\.encoding-stats-chip/);
assert.match(styles, /\.upload-panel/);
assert.match(styles, /\.upload-actions/);
assert.match(styles, /\.upload-progress-fill/);
assert.match(styles, /\.upload-detail-list/);
assert.match(styles, /\.repository-list/);
assert.match(styles, /\.repository-item/);
assert.match(styles, /\.repository-row/);
assert.match(styles, /\.repository-card/);
assert.match(styles, /\.repository-thumbnail/);
assert.match(styles, /\.repository-status/);
assert.match(styles, /\.login-status/);
assert.match(styles, /\.login-dialog/);
assert.match(styles, /@keyframes splash-logo/);
assert.match(styles, /@keyframes splash-exit/);

console.log("App shell behavior check passed.");
