const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const repoRoot = path.resolve(root, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const readRepo = (file) => fs.readFileSync(path.join(repoRoot, file), "utf8");

const packageJson = require(path.join(root, "package.json"));
const packageLock = require(path.join(root, "package-lock.json"));
const builderConfig = read("electron-builder.config.cjs");
const releaseWorkflow = readRepo(".github/workflows/release-installers.yml");
const indexHtml = read("index.html");
const main = read("src/main/main.js");
const preload = read("src/main/preload.js");
const app = read("src/renderer/App.jsx");
const styles = read("src/renderer/styles.css");

assert.equal(packageJson.name, "dl-studio-mac");
assert.equal(packageJson.author, "DL Studio");
assert.equal(packageLock.name, "dl-studio-mac");
assert.equal(packageLock.packages[""].name, "dl-studio-mac");
assert.match(packageJson.dependencies["@ffprobe-installer/ffprobe"], /^\^2\.1\.2/);
assert.match(packageJson.devDependencies.electron, /^\^34\./);
assert.ok(!Object.prototype.hasOwnProperty.call(packageJson, "build"), "electron-builder config must live in electron-builder.config.cjs");
assert.match(builderConfig, /appId: "com\.dlstudio\.mac"/);
assert.match(builderConfig, /productName: "DL Studio"/);
assert.match(builderConfig, /DL_STUDIO_MAC_ARCH/);
assert.match(builderConfig, /npm_config_arch/);
assert.match(builderConfig, /process\.arch/);
assert.match(builderConfig, /node_modules\/ffmpeg-static\/ffmpeg/);
assert.match(builderConfig, /node_modules\/@ffprobe-installer\/darwin-arm64\/ffprobe/);
assert.match(builderConfig, /bin\/ffprobe-arm64/);
assert.match(builderConfig, /node_modules\/ffprobe-static\/bin\/darwin\/x64\/ffprobe/);
assert.match(builderConfig, /bin\/ffprobe-x64/);
assert.match(builderConfig, /artifactName: "DL-Studio-Mac-\$\{version\}-\$\{arch\}\.\$\{ext\}"/);
assert.match(releaseWorkflow, /arch: x64/);
assert.match(releaseWorkflow, /runner: macos-15-intel/);
assert.match(releaseWorkflow, /ffprobe: ffprobe-x64/);
assert.match(releaseWorkflow, /DL_STUDIO_MAC_ARCH: \$\{\{ matrix\.arch \}\}/);
assert.match(releaseWorkflow, /electron-builder --config electron-builder\.config\.cjs --mac dmg pkg --\$\{\{ matrix\.arch \}\}/);
assert.match(indexHtml, /<title>DL Studio<\/title>/);

assert.match(main, /const APP_NAME = "DL Studio"/);
assert.match(main, /app\.setName\(APP_NAME\)/);
assert.match(main, /title: APP_NAME/);
assert.doesNotMatch(main, /frame: false/);
assert.match(main, /titleBarStyle: "hiddenInset"/);
assert.match(main, /titleBarStyle: "hidden"/);
assert.match(main, /titleBarOverlay/);
assert.match(main, /function setTitleBarTheme/);
assert.match(main, /setFullScreen\(/);
assert.match(main, /isFullScreen\(/);
assert.doesNotMatch(main, /mainWindow\.maximize\(\)/);
assert.match(main, /before-input-event/);
assert.match(main, /setZoomLevel\(/);
assert.match(main, /input\.alt/);
assert.match(main, /input\.control/);
assert.match(main, /const INFERA_API_BASE_URL = process\.env\.INFERA_API_BASE_URL \|\| process\.env\.VITE_INFERA_API_BASE_URL \|\| "https:\/\/api\.infera\.cn\/api\/infera"/);
assert.match(main, /const DL_ENGINE_API_BASE_URL = process\.env\.DL_ENGINE_API_BASE_URL \|\| process\.env\.VITE_DL_ENGINE_API_BASE_URL \|\| "http:\/\/127\.0\.0\.1:8787"/);
assert.match(main, /const DL_ENGINE_TENANT_ID = process\.env\.DL_ENGINE_TENANT_ID \|\| process\.env\.DL_LOCAL_QUERY_TENANT_ID/);
assert.match(main, /const DL_ENGINE_USER_ID = process\.env\.DL_ENGINE_USER_ID \|\| process\.env\.DL_LOCAL_QUERY_USER_ID/);
assert.match(main, /function resolveInferaUrl/);
assert.match(main, /function getInferaHttpErrorMessage/);
assert.match(main, /请求失败 \(\$\{Number\(statusCode\) \|\| 0\}\)/);
assert.match(main, /function resolveEngineUrl/);
assert.match(main, /function getEngineAuthorization/);
assert.match(main, /function handleEngineMediaProxyRequest/);
assert.match(main, /function startEngineMediaProxy/);
assert.match(main, /function stopEngineMediaProxy/);
assert.match(main, /function requestEngine/);
assert.match(main, /function streamEngineQa/);
assert.match(main, /parseEngineSseMessage/);
assert.match(main, /responseType === "download"/);
assert.match(main, /function initializeFileLogger/);
assert.match(main, /main\.log/);
assert.match(main, /ipcMain\.handle\("logs:get-main-log-path"/);
assert.match(main, /ipcMain\.handle\("logs:write"/);
assert.match(main, /ipcMain\.handle\("logs:reveal-main-log"/);
assert.match(main, /Renderer console message/);
assert.match(main, /Transcode job state changed/);
assert.match(main, /Upload state changed/);
assert.match(main, /ipcMain\.handle\("infera:request"/);
assert.match(main, /ipcMain\.handle\("engine:request"/);
assert.match(main, /ipcMain\.handle\("engine:qa-stream"/);
assert.match(main, /ipcMain\.handle\("engine:qa-stream:cancel"/);
assert.match(main, /ipcMain\.handle\("engine:get-media-proxy-url"/);
assert.match(main, /responseType === "redirect"/);
assert.match(main, /function uploadInferaVideo/);
assert.match(main, /const activeUploadRequests = new Map/);
assert.match(main, /function normalizeUploadTimestamp/);
assert.match(main, /function normalizeUploadDuration/);
assert.match(main, /function normalizeUploadDurationMs/);
assert.match(main, /require\("@ffprobe-installer\/ffprobe"\)\.path/);
assert.match(main, /Math\.round\(timestamp\)/);
assert.match(main, /function emitUploadProgress/);
assert.match(main, /infera:upload-progress/);
assert.match(main, /payload\.uploadId/);
assert.match(main, /bytesUploaded/);
assert.match(main, /bytesUploaded: uploadedBytes/);
assert.doesNotMatch(main, /sendProgress\("uploading", \{ bytesUploaded, message/);
assert.match(main, /speedBytesPerSecond/);
assert.match(main, /WEB_VIDEO_RESUMABLE_UPLOAD_PATH/);
assert.match(main, /\/memory\/assets\/web-video\/resumable/);
assert.match(main, /function isWebVideoUploadPath/);
assert.match(main, /function getResumableVideoUploadConfig/);
assert.match(main, /kind: "web-video"/);
assert.match(main, /function abortResumableUploadSession/);
assert.match(main, /remoteAbortStarted/);
assert.match(main, /phase: "hashing"/);
assert.match(main, /uploadRecord\.phase = "completing"/);
assert.match(main, /removeRawDataUploadSession\(uploadRecord\.sessionKey\)/);
assert.match(main, /function uploadResumableVideo/);
assert.match(main, /function uploadResumableVideoPart/);
assert.match(main, /startTimestampMs/);
assert.match(main, /config\.resumablePath/);
assert.match(main, /function getUploadHttpErrorMessage/);
assert.match(main, /413 Request Entity Too Large/);
assert.match(main, /client_max_body_size/);
assert.match(main, /\/memory\/assets\/web-video\/events/);
assert.match(main, /multipart\/form-data/);
assert.match(main, /start_timestamp_ms/);
assert.match(main, /durationMs/);
assert.match(main, /duration_seconds/);
assert.match(main, /duration: mediaInfo\?\.duration \|\| 0/);
assert.match(main, /parseInferaUploadEvents/);
assert.match(main, /ipcMain\.handle\("infera:upload-video"/);
assert.match(main, /ipcMain\.handle\("infera:cancel-upload"/);
assert.match(main, /ipcMain\.handle\("infera:pause-upload"/);
assert.match(main, /ipcMain\.handle\("infera:resume-upload"/);
assert.match(main, /function parseFrameRate/);
assert.match(main, /function formatFrameRateLabel/);
assert.match(main, /function parseEncodingProgressLine/);
assert.match(main, /encodingFps/);
assert.match(main, /encodingSpeed/);
assert.match(main, /hardwareEncoding/);
assert.doesNotMatch(main, /payload\.admin/);
assert.match(main, /responseType === "redirect"/);
assert.match(main, /responseType === "download"/);
assert.match(main, /base64: buffer\.toString\("base64"\)/);
assert.match(main, /const frameRate = parseFrameRate/);
assert.match(main, /frameRate,/);
assert.match(main, /frameRateLabel: formatFrameRateLabel\(frameRate\)/);

assert.match(preload, /toggleFullscreenWindow/);
assert.match(preload, /isWindowFullscreen/);
assert.match(preload, /platform: process\.platform/);
assert.match(preload, /setTitleBarTheme: \(theme\) => ipcRenderer\.invoke\("window:set-title-bar-theme", theme\)/);
assert.match(preload, /getMainLogPath: \(\) => ipcRenderer\.invoke\("logs:get-main-log-path"\)/);
assert.match(preload, /writeLog: \(payload\) => ipcRenderer\.invoke\("logs:write", payload\)/);
assert.match(preload, /revealMainLog: \(\) => ipcRenderer\.invoke\("logs:reveal-main-log"\)/);
assert.match(preload, /onWindowFullscreenChange/);
assert.match(preload, /requestInfera: \(payload\) => ipcRenderer\.invoke\("infera:request", payload\)/);
assert.match(preload, /requestEngine: \(payload\) => ipcRenderer\.invoke\("engine:request", payload\)/);
assert.match(preload, /streamEngineQa: \(payload\) => ipcRenderer\.invoke\("engine:qa-stream", payload\)/);
assert.match(preload, /cancelEngineQaStream: \(streamId\) => ipcRenderer\.invoke\("engine:qa-stream:cancel", streamId\)/);
assert.match(preload, /onEngineQaStreamEvent: \(streamId, listener\) => on\(`engine:qa-stream:event:\$\{streamId\}`, listener\)/);
assert.match(preload, /getEngineMediaProxyUrl: \(\) => ipcRenderer\.invoke\("engine:get-media-proxy-url"\)/);
assert.match(preload, /uploadInferaVideo: \(payload\) => ipcRenderer\.invoke\("infera:upload-video", payload\)/);
assert.match(preload, /cancelInferaUpload: \(uploadId\) => ipcRenderer\.invoke\("infera:cancel-upload", uploadId\)/);
assert.match(preload, /pauseInferaUpload: \(uploadId\) => ipcRenderer\.invoke\("infera:pause-upload", uploadId\)/);
assert.match(preload, /resumeInferaUpload: \(uploadId\) => ipcRenderer\.invoke\("infera:resume-upload", uploadId\)/);
assert.match(preload, /onInferaUploadProgress: \(listener\) => on\("infera:upload-progress", listener\)/);

assert.match(app, /name: "DL Studio"/);
assert.match(app, /SplashScreen/);
assert.match(app, /className="splash-screen"/);
assert.match(app, /build\/icon\.svg/);
assert.match(app, /toggleFullscreenWindow/);
assert.match(app, /isWindowFullscreen/);
assert.match(app, /onWindowFullscreenChange/);
assert.match(app, /revealMainLog/);
assert.match(app, /logRendererEvent/);
assert.match(app, /Transfer task started/);
assert.match(app, /Transfer task failed/);
assert.match(app, /activeUploadId/);
assert.match(app, /providedUploadId/);
assert.match(app, /定位日志/);
assert.match(app, /const NAV_ITEMS = \["Editor", "Cloud", "Delphi", "Engine", "Research"\]/);
assert.match(app, /const ENGINE_PASSWORD = "111111"/);
assert.match(app, /const CLOUD_SPACES/);
assert.match(app, /const RESEARCH_PAGE_SIZE = 100/);
assert.match(app, /DL Repository/);
assert.match(app, /DL Rawdata/);
assert.match(app, /showLogin/);
assert.match(app, /LoginDialog/);
assert.match(app, /className="profile-button"/);
assert.match(app, /accountName:/);
assert.match(app, /result\?\.accountName/);
assert.match(app, /result\?\.account_name/);
assert.match(app, /fallbackAccountName/);
assert.match(app, /displayName:/);
assert.match(app, /result\?\.displayName/);
assert.match(app, /result\?\.display_name/);
assert.match(app, /user\?\.displayName/);
assert.match(app, /getAuthDisplayName/);
assert.match(app, /getAuthAccountName/);
assert.match(app, /authState\.displayName \|\| authState\.nickname/);
assert.match(app, /className="login-account-identity"/);
assert.match(app, /accountName && accountName !== displayName/);
assert.match(app, /function getAuthInitial/);
assert.match(app, /className="profile-initial"/);
assert.match(app, /getAuthInitial\(accountName\)/);
assert.match(app, /<span>\{displayName \|\| APP_NAME\}<\/span>/);
assert.doesNotMatch(app, /Infera User/);
assert.doesNotMatch(app, /authState\?\.avatar \?/);
assert.match(app, /className="top-nav"/);
assert.match(app, /className="nav-underline"/);
assert.match(app, /const \[isFullscreen, setIsFullscreen\] = useState\(false\)/);
assert.match(app, /onWindowFullscreenChange\(setIsFullscreen\)/);
assert.match(app, /isWindowFullscreen\(\)\.then\(setIsFullscreen\)/);
assert.match(app, /isFullscreen \? "is-fullscreen" : ""/);
assert.doesNotMatch(app, /title="最小化"/);
assert.doesNotMatch(app, /title=\{isFullscreen \? "退出全屏" : "全屏"\}/);
assert.doesNotMatch(app, /className="chrome-button close"/);
assert.match(styles, /\.app-chrome[\s\S]*height: 42px/);
assert.match(styles, /--chrome-left-inset: 86px/);
assert.match(styles, /\.app-shell\.platform-darwin\.is-fullscreen[\s\S]*--chrome-left-inset: 14px/);
assert.match(styles, /--system-window-controls-width: 138px/);
assert.match(styles, /\.app-chrome[\s\S]*padding: 5px calc\(8px \+ var\(--system-window-controls-width\)\) 5px var\(--chrome-left-inset\)/);
assert.match(styles, /\.window-actions[\s\S]*flex: 0 0 auto/);
assert.match(styles, /\.chrome-button[\s\S]*flex: 0 0 var\(--chrome-tool-button-width\)/);
assert.match(styles, /\.app-shell\.platform-win32 \.chrome-button[\s\S]*border-radius: 0/);
assert.match(app, /useLayoutEffect/);
assert.match(app, /navLabelRefs/);
assert.match(app, /getBoundingClientRect/);
assert.match(app, /className="nav-label"/);
assert.match(app, /style=\{navUnderlineStyle\}/);
assert.match(app, /"--nav-underline-width"/);
assert.match(app, /"--nav-underline-left"/);
assert.match(app, /const INFERA_API_BASE_URL = import\.meta\.env\.VITE_INFERA_API_BASE_URL \|\| "https:\/\/api\.infera\.cn\/api\/infera"/);
assert.match(app, /const DL_ENGINE_API_BASE_URL = import\.meta\.env\.VITE_DL_ENGINE_API_BASE_URL \|\| "http:\/\/127\.0\.0\.1:8787"/);
assert.match(app, /const AUTH_STORAGE_KEY = "dl-studio-auth"/);
assert.match(app, /function inferIdentifierType/);
assert.match(app, /function unwrapInferaResult/);
assert.match(app, /function requestInfera/);
assert.match(app, /function requestInferaRaw/);
assert.match(app, /function refreshInferaAuth/);
assert.match(app, /inferaRefreshPromise/);
assert.match(app, /\/auth\/refresh/);
assert.match(app, /function isInferaUnauthorizedError/);
assert.match(app, /INFERA_AUTH_EXPIRED_MESSAGE/);
assert.match(app, /uploadInferaVideoWithAuthRefresh/);
assert.match(app, /setInferaAuthController/);
assert.match(app, /typeof dlEditor\.requestInfera === "function"/);
assert.match(app, /dlEditor\.requestInfera\(\{ accept, path, method, token, body, responseType \}\)/);
assert.match(app, /function requestEngine/);
assert.match(app, /typeof dlEditor\.requestEngine === "function"/);
assert.match(app, /dlEditor\.requestEngine\(\{ path, method, body \}\)/);
assert.match(app, /function streamEngineQa/);
assert.match(app, /onEngineQaStreamEvent/);
assert.match(app, /handleEngineQaStreamEvent/);
assert.match(app, /getEngineMediaProxyUrl/);
assert.ok(app.includes('const normalizedBase = INFERA_API_BASE_URL.replace(/\\/+$/, "");'));
assert.ok(app.includes('const normalizedPath = rawPath.replace(/^\\/+/, "");'));
assert.ok(app.includes('return new URL(normalizedPath, `${normalizedBase}/`).toString();'));
assert.match(app, /\/auth\/login/);
assert.match(app, /type: inferIdentifierType\(identifier\)/);
assert.match(app, /refreshToken/);
assert.match(app, /Authorization/);
assert.match(app, /Bearer \$\{token\}/);
assert.match(app, /window\.localStorage\?\.setItem\(AUTH_STORAGE_KEY/);
assert.match(app, /activeNav === "Editor"/);
assert.match(app, /activeNav === "Cloud"/);
assert.match(app, /activeNav === "Engine"/);
assert.match(app, /activeNav === "Research"/);
assert.match(app, /CloudRepository/);
assert.match(app, /loadCloudRepository/);
assert.match(app, /activeNav === "Research"/);
assert.match(app, /ResearchPage/);
assert.match(app, /isResearchPermissionDenied/);
assert.match(app, /fetchCurrentUser/);
assert.match(app, /requestInfera\("\/users\/me"/);
assert.match(app, /permissionKey \|\| permission\?\.permission_key/);
assert.match(app, /researchAccessState\.status !== "allowed"/);
assert.match(app, /status: permissionDenied \? "forbidden" : "error"/);
assert.match(app, /state\.status === "forbidden"/);
assert.match(app, /fetchResearchResources/);
assert.match(app, /fetchResearchChats/);
assert.match(app, /ResearchResourcesView/);
assert.match(app, /ResearchChatsView/);
assert.match(app, /ResearchStatisticsView/);
assert.match(app, /resolveResearchSignedUrl/);
assert.match(app, /delivery: "oss"/);
assert.doesNotMatch(app, /asset_ids:[\s\S]{0,160}delivery: "direct"/);
assert.match(app, /exportDownload/);
assert.match(app, /research-download-notice/);
assert.match(app, /再次下载/);
assert.match(styles, /\.research-download-notice/);
assert.match(app, /const CLOUD_REPOSITORY_PAGE_SIZE = 100/);
assert.match(app, /const CLOUD_REPOSITORY_DEFAULT_MEDIA_FILTER_ID = "all"/);
assert.match(app, /const CLOUD_REPOSITORY_DEFAULT_STATUS_FILTER_ID = "all_status"/);
assert.match(app, /function buildCloudRepositoryPagePath/);
assert.match(app, /page_mode: "cursor"/);
assert.match(app, /params\.set\("start_timestamp_ms"/);
assert.match(app, /params\.set\("end_timestamp_ms"/);
assert.match(app, /params\.set\("parse_status"/);
assert.match(app, /function getCloudRepositoryParseStatusParam/);
assert.match(app, /function getCloudMediaFiltersForSpace/);
assert.match(app, /function getCloudStatusFiltersForSpace/);
assert.match(app, /\["all", "video", "audio"\]/);
assert.match(app, /\["all_status", "parsed", "processing", "failed"\]/);
assert.match(app, /const RAW_DATA_LIST_PATH = "\/memory\/raw-data"/);
assert.match(app, /const RAW_DATA_VIDEO_UPLOAD_PATH = "\/memory\/raw-data\/videos"/);
assert.match(app, /const DELPHI_UPLOAD_MAX_BYTES = 2 \* 1024 \* 1024 \* 1024/);
assert.ok(app.includes("const DELPHI_UPLOAD_FILE_NAME_PATTERN = /^\\d{4}_\\d{2}_\\d{2}_\\d{2}_\\d{2}_\\d{2}\\.mp4$/i;"));
assert.match(app, /deleteRawDataArchive/);
assert.match(app, /getRawDataId/);
assert.match(app, /repositoryState/);
assert.match(app, /transferQueue/);
assert.match(app, /transferDockExpanded/);
assert.match(app, /transferRunning/);
assert.match(app, /transferQueueRef/);
assert.match(app, /transferRunningRef/);
assert.match(app, /canAddTransfer/);
assert.match(app, /canStartTransfers/);
assert.match(app, /canClearFinishedTransfers/);
assert.match(app, /enqueueAutomationTransfers/);
assert.match(app, /scheduleTransferQueueStart/);
assert.match(app, /startTransferQueue/);
assert.match(app, /restartFailed = true/);
assert.match(app, /restartFailed: false/);
assert.match(app, /retryTransferTask/);
assert.match(app, /createTransferTask/);
assert.match(app, /getManualDelphiUploadValidationError/);
assert.match(app, /getManualDelphiUploadErrorMessage/);
assert.match(app, /文件需小于 2GB/);
assert.match(app, /yyyy_mm_dd_hh_mm_ss\.mp4/);
assert.match(app, /createJobFromTransferTask/);
assert.match(app, /getTransferTaskUploadOptions/);
assert.match(app, /getPendingAutomationTransferKinds/);
assert.match(app, /getNextTransferTask/);
assert.match(app, /sortTransferQueue/);
assert.match(app, /UploadQueueDock/);
assert.match(app, /TransferQueueItem/);
assert.match(app, /sourceJobId/);
assert.match(app, /autoUploadRequested/);
assert.match(app, /autoBackupRequested/);
assert.match(app, /shouldClearLocalOnComplete/);
assert.match(app, /automationOptionsRef\.current\.autoClearLocal/);
assert.match(app, /destination: isBackup \? "DL Rawdata" : "Delphi Repository"/);
assert.match(app, /if \(job\?\.uploadName\)/);
assert.match(app, /clearLocalTarget: isBackup \? "source" : "output"/);
assert.match(app, /backedUpAt/);
assert.match(app, /deletedOriginalPath/);
assert.match(app, /deletedOutputPath/);
assert.match(app, /clearUploadedLocalFile/);
assert.match(app, /getProcessingDoneMessage/);
assert.match(app, /getProcessingOutputActionPath/);
assert.match(app, /本地压制视频已清除/);
assert.match(app, /处理完成后备份原视频/);
assert.match(app, /备份后清除原视频/);
assert.doesNotMatch(app, /完整视频备份稍后接入/);
assert.match(app, /createUploadItems/);
assert.match(app, /cancelCurrentUpload/);
assert.match(app, /uploadId/);
assert.match(app, /onInferaUploadProgress/);
assert.match(app, /speedBytesPerSecond/);
assert.match(app, /formatUploadSpeed/);
assert.match(app, /getUploadCurrentSpeed/);
assert.match(app, /getTransferErrorStatus/);
assert.match(app, /isTransferErrorStatus/);
assert.match(app, /createTransferFailureSnapshot/);
assert.match(app, /formatJobTransferStatusLabel/);
assert.match(app, /transferFailureSnapshot/);
assert.match(app, /upload_error/);
assert.match(app, /backup_error/);
assert.match(app, /status: canceled \? "canceled" : transferErrorStatus/);
assert.match(app, /toggleCurrentUploadPaused/);
assert.match(app, /pauseInferaUpload/);
assert.match(app, /resumeInferaUpload/);
assert.match(app, /getUploadItemElapsedMs/);
assert.match(app, /getUploadItemRemainingMs/);
assert.match(app, /className="transfer-item-meta"/);
assert.match(app, /耗时 <DurationValue value=\{getUploadItemElapsedMs\(item, now\)\}/);
assert.match(app, /预计剩余 <DurationValue value=\{getUploadItemRemainingMs\(item, now\)\}/);
assert.match(app, /formatBytes\(item\.bytesUploaded, \{ precision: 2 \}\)/);
assert.match(app, /formatBytes\(item\.totalBytes, \{ precision: 2 \}\)/);
assert.match(app, /getActiveEncodingJob/);
assert.match(app, /formatEncodingSpeed/);
assert.match(app, /className="encoding-stats-chip"/);
assert.match(app, /activeEncodingJob/);
assert.match(app, /isLowFrameRateJob/);
assert.match(app, /getJobUploadPath/);
assert.match(app, /dlEditor\.uploadInferaVideo/);
assert.match(app, /\/memory\/assets\/web-video\/events/);
assert.match(app, /className="frame-rate-chip"/);
assert.doesNotMatch(app, /selectionMode/);
assert.doesNotMatch(app, /selectedJobIds/);
assert.doesNotMatch(app, /toggleSelectionMode/);
assert.doesNotMatch(app, /toggleAllSelectedJobs/);
assert.doesNotMatch(app, /backupSelectedJobs/);
assert.doesNotMatch(app, /hasPendingAutomationActions/);
assert.doesNotMatch(app, /enqueueAutomationJobs/);
assert.doesNotMatch(app, /automationDrainTimerRef/);
assert.doesNotMatch(app, /drainAutomationQueue/);
assert.doesNotMatch(app, /mode: "auto-upload"/);
assert.doesNotMatch(app, /mode: "auto-backup"/);
assert.doesNotMatch(app, /autoBackupStatus/);
assert.doesNotMatch(app, /uploadSelectedJobs/);
assert.doesNotMatch(app, /closeUploadPanel/);
assert.doesNotMatch(app, /toggleUploadDetails/);
assert.doesNotMatch(app, /UploadProgressPanel/);
assert.doesNotMatch(app, /TransferStatusChips/);
assert.doesNotMatch(app, /getJobTransferChips/);
assert.doesNotMatch(app, /AutoUploadNotice/);
assert.doesNotMatch(app, /getNextUploadPanelStatus/);
assert.doesNotMatch(app, /className="selection-count"/);
assert.doesNotMatch(app, /className="queue-select-box"/);
assert.doesNotMatch(app, /title="备份所选视频"/);
assert.doesNotMatch(app, /title="上传到 Delphi Repository"/);
assert.match(app, /cloudSpaceId/);
assert.match(app, /setCloudSpaceId/);
assert.match(app, /className="cloud-space-button"/);
assert.match(app, /className="cloud-space-menu"/);
assert.match(app, /const CLOUD_FILTERS/);
assert.match(app, /getCloudRepositoryStats/);
assert.match(app, /cloudQuery/);
assert.match(app, /cloudViewMode/);
assert.match(app, /activeMediaFilter/);
assert.match(app, /activeStatusFilter/);
assert.match(app, /className="cloud-nav-group"/);
assert.match(app, /className="cloud-drive"/);
assert.match(app, /className="cloud-sidebar"/);
assert.match(app, /className="cloud-search"/);
assert.match(app, /className="cloud-view-toggle"/);
assert.match(app, /className="cloud-file-table"/);
assert.match(app, /className="cloud-file-grid"/);
assert.match(app, /className="repository-list"/);
assert.match(app, /className="repository-item"/);
assert.match(app, /RepositoryGridCard/);
assert.match(app, /RepositoryTableRow/);
assert.match(app, /repository-action-menu/);
assert.match(app, /repositoryMenuPosition/);
assert.match(app, /getRepositoryActionMenuPosition/);
assert.match(app, /className="repository-action-menu floating"/);
assert.match(app, /onToggleMenu=\{\(event\) => toggleRepositoryMenu\(item, event\)\}/);
assert.match(app, /getRawDataStorageStatus/);
assert.match(app, /formatRawDataStorageStatus/);
assert.match(app, /storage_status/);
assert.match(app, /save_status/);
assert.match(app, /persist_status/);
assert.match(app, /已保存/);
assert.match(app, /保存中/);
assert.match(app, /保存失败/);
assert.match(app, /<span>状态<\/span>/);
assert.match(app, /上传时间/);
assert.match(app, /拍摄时间/);
assert.match(app, /视频时长/);
assert.match(app, /文件大小/);
assert.match(app, /getRepositoryCapturedTime/);
assert.match(app, /parseRepositoryCapturedTimestampFromName/);
assert.match(app, /parseTimestampFromFileName/);
assert.ok(
  app.indexOf("const fileNameTimestamp = parseRepositoryCapturedTimestampFromName(item);") < app.indexOf("item?.captured_at"),
  "Rawdata captured time should prefer filename parsing before API timestamp fields"
);
assert.match(app, /durationSeconds: job\.duration/);
assert.match(app, /durationMs: Math\.max\(0, Math\.round\(\(Number\(job\.duration\) \|\| 0\) \* 1000\)\) \|\| undefined/);
assert.match(app, /video_duration_seconds/);
assert.match(app, /duration_ms/);
assert.match(app, /thumbnail_url/);
assert.match(app, /summary_text/);
assert.match(app, /parse_status/);
assert.match(app, /media_url/);
assert.match(app, /PlaceholderPage/);
assert.match(app, /title=\{activeNav\}/);
assert.match(app, /EngineGate/);
assert.match(app, /EngineWorkspace/);
assert.match(app, /ResearchPage/);
assert.match(app, /DL Engine/);
assert.match(app, /Research Resources/);
assert.match(app, /fetchResearchResources/);
assert.match(app, /fetchResearchChats/);
assert.match(app, /ResearchStatisticsView/);
assert.match(app, /resolveResearchSignedUrl/);
assert.match(app, /const pageSize = 14/);
assert.match(app, /research-modal-body/);
assert.match(app, /lockEngine/);
assert.match(app, /requestEngine\("\/healthz"\)/);
assert.match(app, /requestEngine\("\/v1\/search"/);
assert.match(app, /requestEngine\("\/v1\/qa"/);
assert.match(app, /include_debug: true/);
assert.match(app, /response_mode: "json"/);
assert.match(app, /response_mode: "sse"/);
assert.match(app, /evidence_reasoning/);
assert.match(app, /retrieval_results/);
assert.match(app, /activeEngineTab/);
assert.match(app, /engineUseVespa/);
assert.match(app, /engineView/);
assert.match(app, /clearEngineWorkspace/);
assert.match(app, /engine-vespa-toggle/);
assert.match(app, /engine-test-view/);
assert.match(app, /engine-main-toolbar/);
assert.match(app, /engine-toolbar-title/);
assert.match(app, /EngineSearchHit/);
assert.match(app, /EngineQueryEntryBody/);
assert.match(app, /getEngineQueryStageLabel/);
assert.match(app, /engine-reasoning-list/);
assert.match(app, /engine-retrieval-result-list/);
assert.match(app, /EngineMediaPreview/);
assert.match(app, /buildEngineMediaUrl/);
assert.match(app, /getEngineRawRefFromReferences/);
assert.match(app, /engine-input-bar/);
assert.match(app, /等待 query/);
assert.doesNotMatch(app, /researchUnlocked/);
assert.match(app, /name="identifier"/);
assert.match(app, /autoComplete="username"/);
assert.match(app, /type="password"/);
assert.match(styles, /\.splash-screen/);
assert.match(styles, /\.profile-button/);
assert.match(styles, /\.top-nav/);
assert.doesNotMatch(styles, /\.top-nav\s*\{[^}]*border:/s);
assert.doesNotMatch(styles, /\.top-nav\s*\{[^}]*background:/s);
assert.match(styles, /\.nav-underline/);
assert.match(styles, /width: var\(--nav-underline-width\)/);
assert.match(styles, /transform: translateX\(var\(--nav-underline-left\)\)/);
assert.match(styles, /\.profile-button svg/);
assert.match(styles, /\.profile-initial/);
assert.match(styles, /place-items: center/);
assert.doesNotMatch(styles, /\.profile-initial\s*\{[^}]*background:/s);
assert.match(styles, /\.login-account-identity/);
assert.match(styles, /\.placeholder-page/);
assert.match(styles, /\.engine-page/);
assert.match(styles, /\.engine-gate/);
assert.match(styles, /\.engine-workspace/);
assert.match(styles, /\.engine-icon-button/);
assert.match(styles, /\.engine-main-toolbar/);
assert.match(styles, /\.engine-toolbar-title/);
assert.match(styles, /\.engine-tabs/);
assert.match(styles, /\.engine-toolbar-actions/);
assert.match(styles, /\.engine-vespa-toggle/);
assert.match(styles, /\.engine-test-view/);
assert.match(styles, /\.engine-hit/);
assert.match(styles, /\.engine-meta-row/);
assert.match(styles, /\.engine-media-preview/);
assert.match(styles, /\.engine-media-caption/);
assert.match(styles, /\.engine-video-frame/);
assert.match(styles, /\.engine-audio-frame/);
assert.match(styles, /\.engine-media-placeholder/);
assert.match(styles, /\.engine-citation/);
assert.match(styles, /\.engine-presenter/);
assert.match(styles, /\.engine-qa-stream/);
assert.match(styles, /\.engine-input-bar/);
assert.match(styles, /\.research-login-page/);
assert.doesNotMatch(styles, /\.auto-upload-notice/);

assert.match(styles, /\.cloud-page/);
assert.match(styles, /\.cloud-drive/);
assert.match(styles, /\.cloud-sidebar/);
assert.match(styles, /\.research-page/);
assert.match(styles, /\.research-tabs/);
assert.match(styles, /\.research-filter-row/);
assert.match(styles, /\.research-workspace/);
assert.match(styles, /\.research-gallery/);
assert.match(styles, /\.research-detail/);
assert.match(styles, /\.research-chat-card/);
assert.match(styles, /\.research-stats-table/);
assert.match(styles, /\.research-modal-body \.research-stats-table/);
assert.equal((styles.match(/\.research-page\s*\{/g) || []).length, 1);
assert.doesNotMatch(styles, /\.research-toolbar/);
assert.match(styles, /\.cloud-brand-icon svg/);
assert.match(styles, /\.cloud-space-button/);
assert.match(styles, /\.cloud-space-menu/);
assert.match(styles, /\.cloud-search/);
assert.match(styles, /\.cloud-view-toggle/);
assert.match(styles, /\.cloud-file-table/);
assert.match(styles, /\.cloud-file-grid/);
assert.doesNotMatch(styles, /\.queue-item\.selection-open/);
assert.doesNotMatch(styles, /\.queue-select-box/);
assert.doesNotMatch(styles, /\.selection-count/);
assert.match(styles, /\.frame-rate-chip/);
assert.match(styles, /\.encoding-stats-chip/);
assert.doesNotMatch(styles, /\.transfer-status-chip/);
assert.doesNotMatch(styles, /\.upload-panel/);
assert.doesNotMatch(styles, /\.upload-actions/);
assert.match(styles, /\.upload-progress-fill/);
assert.doesNotMatch(styles, /\.upload-detail-list/);
assert.doesNotMatch(styles, /\.upload-detail-time/);
assert.match(styles, /\.transfer-dock/);
assert.match(styles, /\.transfer-fab/);
assert.match(styles, /\.transfer-dock-panel/);
assert.match(styles, /\.transfer-dock-actions/);
assert.match(styles, /\.transfer-item/);
assert.match(styles, /\.transfer-retry-button/);
assert.match(styles, /\.repository-list/);
assert.match(styles, /\.repository-item/);
assert.match(styles, /\.repository-row/);
assert.match(styles, /\.repository-row\.rawdata/);
assert.match(styles, /\.repository-action-menu/);
assert.match(styles, /\.repository-action-menu\.floating/);
assert.match(styles, /position: fixed/);
assert.match(styles, /top: var\(--menu-top\)/);
assert.match(styles, /left: var\(--menu-left\)/);
assert.match(styles, /\.repository-card/);
assert.match(styles, /\.repository-thumbnail/);
assert.match(styles, /\.repository-status/);
assert.match(styles, /\.repository-status\.storage\.saved/);
assert.match(styles, /\.repository-status\.storage\.processing/);
assert.match(styles, /\.repository-status\.storage\.failed/);
assert.match(styles, /\.login-status/);
assert.match(styles, /\.login-dialog/);
assert.match(styles, /@keyframes splash-logo/);
assert.match(styles, /@keyframes splash-exit/);

console.log("App shell behavior check passed.");
